export default {
    MASJIDLOGO : require("../assets/images/masjidlogo.png"),
    FAVORITES : require("../assets/images/favorites.png"),
    RIGHTARROW : require("../assets/images/rightarrow.png"),
    AQSAMAS : require("../assets/images/aqsamas.png"),
    MASJID : require("../assets/images/masjid.jpg"),
    MAKKAH : require("../assets/images/makkah.jpg"),
    MOSQUE : require("../assets/images/mosque.jpg"),
    KARACHI : require("../assets/images/karachi.jpg"),
    MUSAFAR : require("../assets/images/musafar.jpg"),
    SABAH : require("../assets/images/sabah.jpg"),
    MALAYSIA : require("../assets/images/malaysia.jpg"),
    FLOAT: require("../assets/images/float.jpg"),
    MALIK: require("../assets/images/malik.jpg"),
    PIRAMID: require("../assets/images/piramid.jpg"),
    UBDHIH: require("../assets/images/ubdhih.jpg"),
    DAWOOD: require("../assets/images/dawood.jpg"),
    CHINA: require("../assets/images/china.jpg"),
    CROSS: require("../assets/images/cross.png"),
    LOADING: require("../assets/images/loadingwhite.json"),
};